import { DocExporter, DocMeta } from './types';
import { ApiEntry } from '../html-generator';
import { ClientApiEntry } from '../client-api-scanner';
import { ParamInfo } from '../ast-parser';

/**
 * OpenAPI 3.0 내보내기
 * 서버 라우트 + 클라이언트 호출을 OpenAPI 스펙으로 변환합니다.
 * 외부 의존성 없이 JSON 출력 (YAML이 필요하면 js-yaml 추가)
 */
export class OpenApiExporter implements DocExporter {
  format = 'openapi';
  extension = 'json';

  generate(
    serverEntries: ApiEntry[],
    clientEntries: ClientApiEntry[],
    meta: DocMeta
  ): string {
    const spec: any = {
      openapi: '3.0.3',
      info: {
        title: meta.projectName,
        version: meta.version ?? '1.0.0',
        description: `Auto-generated by fe-api-tracer at ${meta.generatedAt}`,
      },
      paths: {},
    };

    // 서버 엔트리 → paths
    for (const entry of serverEntries) {
      const pathKey = this.toOpenApiPath(entry.route.routePath);
      if (!spec.paths[pathKey]) spec.paths[pathKey] = {};

      for (const method of entry.endpoint.methods) {
        const m = method.toLowerCase();
        if (m === 'all') continue;
        spec.paths[pathKey][m] = this.buildOperation(
          entry.endpoint.description,
          entry.endpoint.params,
          entry.endpoint.returns,
          entry.route.relativePath
        );
      }
    }

    // 클라이언트 엔트리 → paths (서버에 없는 것만 추가)
    for (const entry of clientEntries) {
      const pathKey = this.toOpenApiPath(entry.url);
      if (!spec.paths[pathKey]) spec.paths[pathKey] = {};

      const m = entry.method.toLowerCase();
      if (m === 'all') continue;
      if (spec.paths[pathKey][m]) continue; // 서버에서 이미 정의됨

      spec.paths[pathKey][m] = this.buildOperation(
        entry.description,
        entry.params,
        entry.returns,
        entry.sourceFile
      );
    }

    return JSON.stringify(spec, null, 2);
  }

  /** /api/user/:id → /api/user/{id} */
  private toOpenApiPath(routePath: string): string {
    return routePath
      .replace(/:(\w+)/g, '{$1}')
      .replace(/\*(\w+)/g, '{$1}');
  }

  private buildOperation(
    description: string,
    params: ParamInfo[],
    returns: { type: string; description: string } | null,
    source: string
  ): any {
    const operation: any = {
      description: description || undefined,
      'x-source': source,
      responses: {
        '200': {
          description: 'Successful response',
        },
      },
    };

    if (returns) {
      operation.responses['200'].content = {
        'application/json': {
          schema: { type: this.mapType(returns.type) },
          ...(returns.description ? { description: returns.description } : {}),
        },
      };
    }

    if (params.length > 0) {
      operation.requestBody = {
        required: params.some((p) => p.required),
        content: {
          'application/json': {
            schema: {
              type: 'object',
              required: params.filter((p) => p.required).map((p) => p.name),
              properties: Object.fromEntries(
                params.map((p) => [
                  p.name,
                  {
                    type: this.mapType(p.type),
                    description: p.description || undefined,
                  },
                ])
              ),
            },
          },
        },
      };
    }

    return operation;
  }

  private mapType(tsType: string): string {
    const t = tsType.toLowerCase();
    if (t === 'number' || t === 'int' || t === 'float') return 'number';
    if (t === 'boolean' || t === 'bool') return 'boolean';
    if (t === 'string') return 'string';
    if (t.includes('[]') || t.startsWith('array')) return 'array';
    return 'string';
  }
}
