import { DocExporter, DocMeta } from './types';
import { ApiEntry } from '../html-generator';
import { ClientApiEntry } from '../client-api-scanner';

interface PostmanItem {
  name: string;
  request: {
    method: string;
    url: { raw: string; host: string[]; path: string[] };
    body?: any;
    description?: string;
  };
}

/**
 * Postman Collection v2.1 내보내기
 */
export class PostmanExporter implements DocExporter {
  format = 'postman';
  extension = 'json';

  generate(
    serverEntries: ApiEntry[],
    clientEntries: ClientApiEntry[],
    meta: DocMeta
  ): string {
    const collection: any = {
      info: {
        name: meta.projectName,
        description: `Auto-generated by fe-api-tracer at ${meta.generatedAt}`,
        schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
      },
      item: [],
      variable: [
        { key: 'baseUrl', value: 'http://localhost:3000', type: 'string' },
      ],
    };

    // 그룹별 폴더
    const groups = new Map<string, PostmanItem[]>();

    // 서버 엔트리
    for (const entry of serverEntries) {
      for (const method of entry.endpoint.methods) {
        if (method === 'ALL') continue;
        const group = entry.route.group;
        if (!groups.has(group)) groups.set(group, []);
        groups.get(group)!.push(this.buildServerItem(entry, method));
      }
    }

    // 클라이언트 엔트리
    for (const entry of clientEntries) {
      const group = entry.group;
      if (!groups.has(group)) groups.set(group, []);
      groups.get(group)!.push(this.buildClientItem(entry));
    }

    // 폴더 구성
    for (const [groupName, items] of groups) {
      collection.item.push({
        name: groupName,
        item: items,
      });
    }

    return JSON.stringify(collection, null, 2);
  }

  private buildServerItem(entry: ApiEntry, method: string): PostmanItem {
    const url = entry.route.routePath;
    const pathSegments = url.split('/').filter(Boolean);

    const item: PostmanItem = {
      name: `${method} ${url}`,
      request: {
        method,
        url: {
          raw: `{{baseUrl}}${url}`,
          host: ['{{baseUrl}}'],
          path: pathSegments,
        },
        description: entry.endpoint.description || undefined,
      },
    };

    if (method !== 'GET' && entry.endpoint.params.length > 0) {
      item.request.body = {
        mode: 'raw',
        raw: JSON.stringify(
          Object.fromEntries(entry.endpoint.params.map((p) => [p.name, `<${p.type}>`])),
          null, 2
        ),
        options: { raw: { language: 'json' } },
      };
    }

    return item;
  }

  private buildClientItem(entry: ClientApiEntry): PostmanItem {
    const url = entry.url;
    const pathSegments = url.split('/').filter(Boolean);

    const item: PostmanItem = {
      name: `${entry.method} ${url}`,
      request: {
        method: entry.method,
        url: {
          raw: `{{baseUrl}}${url}`,
          host: ['{{baseUrl}}'],
          path: pathSegments,
        },
        description: entry.description || undefined,
      },
    };

    if (entry.method !== 'GET' && entry.params.length > 0) {
      item.request.body = {
        mode: 'raw',
        raw: JSON.stringify(
          Object.fromEntries(entry.params.map((p) => [p.name, `<${p.type}>`])),
          null, 2
        ),
        options: { raw: { language: 'json' } },
      };
    }

    return item;
  }
}
